# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Backend and deploy to DEV

on:
  push:
    branches:
      - infrastructure/otc
    paths:
      - backend/**
      - .github/workflows/backend*.yml

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - name: Set up CF CLI
        if: success()
        uses: jvalkeal/setup-cf-cli@v0
        with:
          version: 6.51.0

      - name: CF Login
        if: success()
        run: cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
        env:
          CF_API: ${{ secrets.CF_OTC_API }}
          CF_ORG: ${{ secrets.CF_OTC_ORG }}
          CF_SPACE: ${{ secrets.CF_OTC_SPACE_INTERNAL }}
          CF_USERNAME: ${{ secrets.CF_OTC_BUILD_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_OTC_BUILD_PASSWORD }}

      - name: Deploy Backend DEV
        if: success()
        run: cf push internal-dev-backend -f ./manifest-otc.yml -t 180
