# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Backend and deploy to TEST

on:
  push:
    branches:
      - stage-on-test
    paths:
      - backend/**
      - .github/workflows/backend*.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml

    - name: Set up CF CLI
      if: success()
      uses: jvalkeal/setup-cf-cli-action@master
      with:
        version: 6.51.0

    - name: CF Login
      if: success()
      run: cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}

    - name: Deploy Backend TEST
      if: success()
      run: cf push quarano-backend-test
