# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to CUX TEST

on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - frontend/**
      - .github/workflows/deployment-test-cux.yml

defaults:
  run:
    shell: bash

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - name: Set up CF CLI
        if: success()
        uses: jvalkeal/setup-cf-cli@v0
        with:
          version: 6.51.0

      - name: CF Login
        if: success()
        run: cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
        env:
          CF_API: ${{ secrets.CF_OTC_API }}
          CF_ORG: ${{ secrets.CF_OTC_ORG }}
          CF_SPACE: ${{ secrets.CF_OTC_SPACE_CUSTOMERS }}
          CF_USERNAME: ${{ secrets.CF_OTC_BUILD_CUSTOMERS_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_OTC_BUILD_CUSTOMERS_PASSWORD }}

      - name: Deploy Backend DEV
        if: success()
        run: cf push quarano-cuxhaven-stage-backend -f ./manifest-otc.yml -t 180

  deploy-frontend:
    timeout-minutes: 15

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build-cuxhaven-stage
      - run: npm run prepare-deployment-otc
      - run: npm run ci-test
      - run: npm run lint

      - name: Set up CF CLI
        if: success()
        uses: jvalkeal/setup-cf-cli@v0
        with:
          version: 6.51.0

      - name: CF Login
        if: success()
        run: cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
        env:
          CF_API: ${{ secrets.CF_OTC_API }}
          CF_ORG: ${{ secrets.CF_OTC_ORG }}
          CF_SPACE: ${{ secrets.CF_OTC_SPACE_CUSTOMERS }}
          CF_USERNAME: ${{ secrets.CF_OTC_BUILD_CUSTOMERS_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_OTC_BUILD_CUSTOMERS_PASSWORD }}

      - name: Deploy Frontend STAGE
        if: success()
        run: cf push quarano-cuxhaven-stage-frontend -f ../manifest-otc.yml
