# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Frontend and deploy to DEMO environment

on:
  push:
    branches:
      - stage-on-demo
    paths:
      - frontend/**
      - .github/workflows/frontend*.yml
      - manifest-otc.yml

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  build:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build-internal-demo
      - run: npm run prepare-deployment-otc

      - name: Deploy Frontend DEMO        
        if: success()
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_OTC_API }}
          cf_org: ${{ secrets.CF_OTC_ORG }}
          cf_space: ${{ secrets.CF_OTC_SPACE_INTERNAL }}
          cf_username: ${{ secrets.CF_OTC_BUILD_USERNAME }}
          cf_password: ${{ secrets.CF_OTC_BUILD_PASSWORD }}
          command: push internal-demo-frontend -f ./manifest-otc.yml
